server:
  port: 9000

spring:
  application:
    name: online-taxi-gateway

eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka-7901:7901/eureka/

  instance:
    hostname: localhost
    instance-id: online-taxi-gateway
