#服务端口
server:
  port: 7902


#应用名称以及验证账号
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root

eureka:
   #server:
    #enable-self-preservation: false #关闭保护机制
    #eviction-interval-timer-in-ms: 2000 #剔除失效服务间隔,单位毫秒
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://root:root@eureka-7901:7901/eureka/,http://root:root@eureka-7902:7902/eureka/,http://root:root@eureka-7903:7903/eureka/
   instance:
      hostname: eureka-7902