server:
  port: 9001

#spring应用名称
spring:
  application:
    name: api-passenger
  redis:
    datasource: 0
    host: 192.168.231.129
    port: 6379
    timeout: 2000
# 是否在启动的时候加载这个servlet >=0时 启动时加载
#  mvc:
#    servlet:
#      load-on-startup: 1

  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1，百分之八采样
  sleuth:
    sampler:
      rate: 1

eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://root:root@eureka-7901:7901/eureka/,http://root:root@eureka-7902:7902/eureka/,http://root:root@eureka-7903:7903/eureka/
  instance:
    hostname: localhost
    instance-id: api-passenger
#feign:
#  hystrix:
#    enabled: true

ribbon:
  eager-load:
    enabled: true
    clients:
      - SERVICE-SMS


#Admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true

logging:
  level:
    org.springframework: DEBUG