server:
  port: 9002

spring:
  application:
    name: api-passenger

eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://localhost:7901/eureka/
    fetch-registry: true
    register-with-eureka: true