server:
  port: 9001

#spring应用名称
spring:
  application:
    name: api-passenger
  redis:
    datasource: 0
    host: 192.168.231.129
    port: 6379
    timeout: 2000
# 是否在启动的时候加载这个servlet >=0时 启动时加载
  mvc:
    servlet:
      load-on-startup: 1

eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://root:root@eureka-7901:7901/eureka/,http://root:root@eureka-7902:7902/eureka/,http://root:root@eureka-7903:7903/eureka/
  instance:
    hostname: localhost
    instance-id: api-passenger
feign:
  hystrix:
    enabled: true